graph [
   comment "Generated by ViSiDiA" 
   node [
      id 0
      graphics [
         x 374
         y 224
      ]
   ]
   node [
      id 1
      graphics [
         x 231
         y 121
      ]
   ]
   node [
      id 2
      graphics [
         x 405
         y 99
      ]
   ]
   node [
      id 3
      graphics [
         x 525
         y 214
      ]
   ]
   node [
      id 4
      graphics [
         x 427
         y 387
      ]
   ]
   edge [
      source 0
      target 1
   ]
   edge [
      source 0
      target 2
   ]
   edge [
      source 0
      target 3
   ]
   edge [
      source 0
      target 4
   ]
]