graph [
   comment "Generated by ViSiDiA" 
   node [
      id 0
      graphics [
         x 240
         y 133
      ]
   ]
   node [
      id 1
      graphics [
         x 469
         y 142
      ]
   ]
   node [
      id 2
      graphics [
         x 197
         y 327
      ]
   ]
   node [
      id 3
      graphics [
         x 371
         y 367
      ]
   ]
   node [
      id 4
      graphics [
         x 517
         y 292
      ]
   ]
   edge [
      source 0
      target 1
   ]
   edge [
      source 0
      target 2
   ]
   edge [
      source 0
      target 3
   ]
   edge [
      source 0
      target 4
   ]
   edge [
      source 1
      target 2
   ]
   edge [
      source 1
      target 3
   ]
   edge [
      source 1
      target 4
   ]
   edge [
      source 2
      target 3
   ]
   edge [
      source 2
      target 4
   ]
   edge [
      source 3
      target 4
   ]
]