graph [
   comment "Generated by ViSiDiA" 
   node [
      id 0
      graphics [
         x 174
         y 175
      ]
   ]
   node [
      id 1
      graphics [
         x 523
         y 175
      ]
   ]
   edge [
      source 0
      target 1
   ]
]